export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 45,
  followers: 1495,
  following: 100,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};
// export default {
//   "login": "RishabhAgarwal123",
//   "id": 41911876,
//   "node_id": "MDQ6VXNlcjQxOTExODc2",
//   "avatar_url": "https://avatars.githubusercontent.com/u/41911876?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/RishabhAgarwal123",
//   "html_url": "https://github.com/RishabhAgarwal123",
//   "followers_url": "https://api.github.com/users/RishabhAgarwal123/followers",
//   "following_url": "https://api.github.com/users/RishabhAgarwal123/following{/other_user}",
//   "gists_url": "https://api.github.com/users/RishabhAgarwal123/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/RishabhAgarwal123/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/RishabhAgarwal123/subscriptions",
//   "organizations_url": "https://api.github.com/users/RishabhAgarwal123/orgs",
//   "repos_url": "https://api.github.com/users/RishabhAgarwal123/repos",
//   "events_url": "https://api.github.com/users/RishabhAgarwal123/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/RishabhAgarwal123/received_events",
//   "type": "User",
//   "site_admin": false,
//   "name": "Rishabh Agarwal",
//   "company": null,
//   "blog": "",
//   "location": "Pune",
//   "email": null,
//   "hireable": null,
//   "bio": "Web Developer",
//   "twitter_username": null,
//   "public_repos": 6,
//   "public_gists": 0,
//   "followers": 0,
//   "following": 0,
//   "created_at": "2018-07-30T14:39:37Z",
//   "updated_at": "2021-09-09T18:18:50Z"
// };
